### ISSUE TITLE
Handling replaceState

### ISSUE THREAD

**Issue by joshuabremer** [jelhan/ember-cli-browser-navigation-button-test-helpers#2]
The reason I'm using this is to test that I'm replacing the state and removing an item from the history. I'm trying to figure out a solution with your library, but it's worth bringing up as an issue.

**Comment by jelhan** [comment]
Sounds interesting. I guess you are trying to trigger back button after history manipulation should have happened and testing URL afterwards, aren't you? Let me know if it works out for you.

**Comment by jelhan** [comment]
Test helpers provided by this addon does not use the history directly. Instead they are recording the transitions done by ember router and using ember router to go back / forward if request. If I understand you correctly, your are manipulating the history directly. Therefore I don't think this test helpers could be used.
