### ISSUE TITLE
Handling transition substates

### ISSUE THREAD

**Issue by L-Yeiser** [jelhan/ember-cli-browser-navigation-button-test-helpers#5]
The history service created tracks `currentPath` and includes `loading` and `error`substates.

Say I have the routes:
```
this.route('blogs', function() {
  this.route('search')
  this.route('blog', { path: '/:id' }, function () {
    this.route('summary')
  })
})
```
and the template `templates/blogs/blog/loading`. When I transition from `blogs` to `blogs.blog.summary` I will first enter the substate `blogs.blog.loading`. At this point the history service will be `['blogs', 'blogs.blog.loading', 'blogs.blog.summary']`. Calling `backButton` will attempt a full transition into `blogs.blog.loading` which will error. The history should only track full transitions.

**Comment by jelhan** [comment]
@L-Yeiser Thanks for your report. Could you please test if #6 fixes your issue?

**Comment by L-Yeiser** [comment]
@jelhan works as expected. Thanks!
